name: Build Electron App

on:
  workflow_dispatch:  # Trigger only on manual dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Specify the OS runners you want to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t electron-app-builder .

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/app electron-app-builder

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ runner.os }}
          path: out/
