name: Build Electron App

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker container
        run: |
          docker build -t electron-app-builder .
          docker run --rm -v ${{ github.workspace }}:/usr/src/app -v /usr/src/app/node_modules electron-app-builder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MUWA-1.7.0-${{ runner.os }}
          path: out/
