name: Build Electron App

on:
  workflow_dispatch:  # Trigger only on manual dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Specify the OS runners you want to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Docker service
        if: runner.os == 'Linux'
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log Docker version
        run: docker --version

      - name: Log Docker Buildx version
        run: docker buildx version

      - name: Build Docker image
        run: docker build -t electron-app-builder .

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/usr/src/app electron-app-builder

      - name: List output directory
        run: ls -alh out/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ runner.os }}
          path: out/
